kind: pipeline
type: docker
name: aa-publish

steps:
  - name: production-release-build
    image: alpine
    commands:
      - apk add zip
      - zip release.zip *

trigger:
  branch:
    - unstable