kind: pipeline
type: docker
name: aa-publish

steps:
  - name: install-prerequisits
    image: alpine
    commands:
      - apk add zip

  - name: production-release-build
    image: alpine
    commands:
      - zip release.zip *


trigger:
  branch:
    - unstable